# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def add_base_document(self, schema_editor):
        self.get_model("ratings", "BaseDocument").objects.create(
            kind=1,
            description='Распоряжение префектуры САО от 08.09.2016 №532',
            description_imp='распоряжением префектуры САО от 08.09.2016 №532'
        )

    initial = True

    dependencies = [
        ('map', '0001_initial'),
        ('employees', '0004_auto_20170220_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'Основной'), (2, 'Показатель')])),
                ('description', models.TextField(unique=True)),
                ('description_imp', models.TextField(unique=True)),
            ],
        ),
        migrations.RunPython(add_base_document),
        migrations.CreateModel(
            name='MonthlyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_negotiated', models.BooleanField(default=False, verbose_name='Согласован')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Утвержден')),
                ('year', models.SmallIntegerField(choices=[(2016, 2016), (2017, 2017)], verbose_name='Год')),
                ('month', models.SmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.PrefectureEmployee')),
                ('base_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.BaseDocument')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRatingComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_description', models.TextField(blank=True, null=True)),
                ('negotiator_comment', models.TextField(blank=True, null=True)),
                ('region_comment', models.TextField(blank=True, null=True)),
                ('year', models.SmallIntegerField(choices=[(2016, 2016), (2017, 2017)], verbose_name='Год')),
                ('month', models.SmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц')),
            ],
            options={
                'ordering': ('-year', '-month'),
                'verbose_name': 'Месячный компонент рейтинга',
                'verbose_name_plural': 'Месячные компоненты рейтингов',
            },
        ),
        migrations.CreateModel(
            name='MonthlyRatingSubComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('best_type', models.CharField(choices=[('мин', 'мин'), ('макс', 'макс')], max_length=10, unique=True)),
                ('document', models.FileField(upload_to='uploads/%Y/%m/%d/documents/')),
                ('monthly_rating_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.MonthlyRatingComponent')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRatingSubComponentValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_average', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monthly_rating_sub_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.MonthlyRatingSubComponent')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Region')),
            ],
        ),
        migrations.CreateModel(
            name='RatingComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True, verbose_name='Наименование')),
                ('base_description', models.TextField(verbose_name='Базовое описание')),
                ('weight', models.SmallIntegerField()),
                ('valid_from_month', models.SmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], db_index=True, verbose_name='Действует с месяца')),
                ('valid_to_month', models.SmallIntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], db_index=True, null=True, verbose_name='Действует по месяц')),
                ('valid_from_year', models.SmallIntegerField(choices=[(2016, 2016), (2017, 2017)], db_index=True, verbose_name='Действует с года')),
                ('valid_to_year', models.SmallIntegerField(blank=True, choices=[(2016, 2016), (2017, 2017)], db_index=True, null=True, verbose_name='Действует по год')),
                ('base_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.BaseDocument')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.PrefectureEmployee', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Базовый компонент рейтинга',
                'verbose_name_plural': 'Базовые компоненты рейтинга',
            },
        ),
        migrations.AddField(
            model_name='monthlyratingsubcomponent',
            name='regions',
            field=models.ManyToManyField(related_name='monthly_rating_sub_components', through='ratings.MonthlyRatingSubComponentValue', to='map.Region'),
        ),
        migrations.AddField(
            model_name='monthlyratingsubcomponent',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.PrefectureEmployee'),
        ),
        migrations.AddField(
            model_name='monthlyratingcomponent',
            name='rating_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.RatingComponent'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyratingsubcomponentvalue',
            unique_together=set([('region', 'monthly_rating_sub_component')]),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyratingcomponent',
            unique_together=set([('rating_component', 'year', 'month')]),
        ),
        migrations.AlterIndexTogether(
            name='monthlyratingcomponent',
            index_together=set([('year', 'month')]),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyrating',
            unique_together=set([('year', 'month')]),
        ),
    ]
