# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_negotiated', models.BooleanField(default=False, verbose_name='Согласован')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Утвержден')),
                ('year', models.SmallIntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017)], verbose_name='Год')),
                ('month', models.SmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.PrefectureEmployee')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRatingComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_description', models.TextField(blank=True, null=True)),
                ('negotiator_comment', models.TextField(blank=True, null=True)),
                ('year', models.SmallIntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017)], verbose_name='Год')),
                ('month', models.SmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRatingSubComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('monthly_rating_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.MonthlyRatingComponent')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.PrefectureEmployee')),
            ],
        ),
        migrations.CreateModel(
            name='RatingComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('description', models.TextField()),
                ('valid_from_year', models.SmallIntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017)], db_index=True, verbose_name='Год')),
                ('valid_to_year', models.SmallIntegerField(blank=True, choices=[(2015, 2015), (2016, 2016), (2017, 2017)], db_index=True, null=True, verbose_name='Год')),
                ('valid_from_month', models.SmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], db_index=True, verbose_name='Год')),
                ('valid_to_month', models.SmallIntegerField(blank=True, choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], db_index=True, null=True, verbose_name='Год')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.PrefectureEmployee')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.AddField(
            model_name='monthlyratingcomponent',
            name='rating_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.RatingComponent'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyratingcomponent',
            unique_together=set([('rating_component', 'year', 'month')]),
        ),
        migrations.AlterIndexTogether(
            name='monthlyratingcomponent',
            index_together=set([('year', 'month')]),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyrating',
            unique_together=set([('year', 'month')]),
        ),
    ]
