# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingelement',
            options={'ordering': ('id',), 'verbose_name': 'Базовый компонент рейтинга', 'verbose_name_plural': 'Базовые компоненты рейтинга'},
        ),
        migrations.RemoveField(
            model_name='ratingelement',
            name='number',
        ),
        migrations.AddField(
            model_name='monthlyratingelement',
            name='number',
            field=models.PositiveIntegerField(null=True, verbose_name='№ п/п'),
        ),
    ]
