# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 09:11
from __future__ import unicode_literals

from django.db import migrations

from apps.ratings.models import MonthlyRatingElement


class Migration(migrations.Migration):

    def enumerate_monthly_elements(self, *args):
        for idx, el in enumerate(MonthlyRatingElement.objects.all()):
            el.number = idx + 1
            el.save()

    dependencies = [
        ('ratings', '0002_auto_20170328_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyratingelement',
            options={'ordering': ('id',), 'verbose_name': 'Компонент месячного рейтинга', 'verbose_name_plural': 'Компоненты месячного рейтинга'},
        ),
        migrations.RunPython(enumerate_monthly_elements)
    ]
