# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20170323_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyratingsubelement',
            options={'ordering': ('name',), 'verbose_name': 'Подкомпонент месячного рейтинга', 'verbose_name_plural': 'Подкомпоненты месячных рейтингов'},
        ),
        migrations.AlterModelOptions(
            name='monthlyratingsubelementvalue',
            options={'ordering': ('id',), 'verbose_name': 'Значение подкомпонента месячного рейтинга', 'verbose_name_plural': 'Значения подкомпонентов месячных рейтингов'},
        ),
        migrations.AddField(
            model_name='monthlyratingelement',
            name='best_type',
            field=models.SmallIntegerField(choices=[(1, 'мин'), (2, 'макс')], default=1),
            preserve_default=False,
        ),
    ]
