# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20170326_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyratingelement',
            name='best_type',
            field=models.SmallIntegerField(choices=[(1, 'мин'), (2, 'макс')], null=True),
        ),
    ]
