# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.District', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.Region', verbose_name='Район'),
        ),
    ]
