# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20170212_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefectureemployee',
            options={'ordering': ('district', 'last_name'), 'verbose_name': 'Сотрудник префектуры', 'verbose_name_plural': 'Сотрудники префектуры'},
        ),
        migrations.AlterModelOptions(
            name='regionemployee',
            options={'ordering': ('region', 'last_name'), 'verbose_name': 'Сотрудник района', 'verbose_name_plural': 'Сотрудники района'},
        ),
    ]
